# Generated by Django 6.0.6 on 2026-06-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_company_name_alter_business_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListingPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='businesses.businesslistingplan')),
            ],
        ),
    ]
