# Generated by Django 6.0.6 on 2026-06-23 08:58
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("field_key", models.SlugField(blank=True, max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("textarea", "Textarea"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("select", "Select"),
                            ("range", "Range"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='Options for checkbox, radio, select fields. e.g. ["Boys PG", "Girls PG"]',
                        null=True,
                    ),
                ),
                (
                    "show_as_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Show this field as a filter on listing page",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Field",
                "verbose_name_plural": "Category Fields",
                "ordering": ["order"],
            },
        ),
    ]
