# Generated by Django 6.0.6 on 2026-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Used as the background/banner photo on homepage featured category cards', null=True, upload_to='categories/banners/'),
        ),
    ]
