# Generated by Django 6.0.6 on 2026-06-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_image',
        ),
    ]
