# Generated by Django 6.0.6 on 2026-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Used as the background/banner photo on homepage featured category cards', null=True, upload_to='categories/banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code for the card background/accent, e.g. #0F9D58', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_card',
            field=models.BooleanField(default=False, help_text='Show this category as a featured card on the homepage'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order of featured cards on the homepage (lower number = shown first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Short tagline shown on the featured card, e.g. 'Trusted consultants'", max_length=255, null=True),
        ),
    ]
