# Generated by Django 6.0.6 on 2026-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_banner_image_category_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, help_text='External link associated with this category', null=True),
        ),
    ]
