# Generated by Django 6.0.6 on 2026-06-23 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_tag', models.CharField(default='ABOUT JUSTKLICK', max_length=100)),
                ('main_title', models.CharField(help_text='Main heading', max_length=255)),
                ('main_description', models.TextField(help_text='About section description')),
                ('button_text', models.CharField(default='Explore Features', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('about_image', models.ImageField(upload_to='about/')),
                ('top_badge_text', models.CharField(default='Verified Education Services', max_length=100)),
                ('trust_card_title', models.CharField(default='Trusted', max_length=100)),
                ('trust_card_subtitle', models.CharField(default='Student Services', max_length=100)),
                ('visitors_icon', models.CharField(max_length=100)),
                ('visitors_count', models.CharField(max_length=50)),
                ('visitors_label', models.CharField(default='Visitors', max_length=50)),
                ('students_icon', models.CharField(max_length=100)),
                ('students_count', models.CharField(max_length=50)),
                ('students_label', models.CharField(default='Students', max_length=50)),
                ('businesses_icon', models.CharField(max_length=100)),
                ('businesses_count', models.CharField(max_length=50)),
                ('businesses_label', models.CharField(default='Businesses', max_length=50)),
                ('feature_one_icon', models.CharField(max_length=100)),
                ('feature_one_title', models.CharField(default='Verified Providers', max_length=100)),
                ('feature_two_icon', models.CharField(max_length=100)),
                ('feature_two_title', models.CharField(default='Student Enquiries', max_length=100)),
                ('feature_three_icon', models.CharField(max_length=100)),
                ('feature_three_title', models.CharField(default='Smart Discovery', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='BulkPartnerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('form_title', models.CharField(default='Send Us a Message', max_length=255)),
                ('button_text', models.CharField(default='Submit Message', max_length=100)),
                ('map_iframe', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromiseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Example: OUR PROMISE', max_length=100)),
                ('title', models.CharField(help_text='Main Heading', max_length=255)),
                ('description', models.TextField(help_text='Section Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='OUR TEAM', max_length=100)),
                ('title', models.CharField(default='Leadership behind JustKlick', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('member_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_places/')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are_badge', models.CharField(default='WHO WE ARE', help_text='Small pill label above the hero title.', max_length=60)),
                ('hero_title', models.CharField(help_text="Main heading, e.g. 'Built to simplify trusted local discovery.'", max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('mission_icon', models.CharField(default='bi bi-flag', help_text='Bootstrap icon class, e.g. bi bi-flag', max_length=60)),
                ('mission_title', models.CharField(default='Our mission', max_length=120)),
                ('mission_description', models.TextField(blank=True)),
                ('popular_services_title', models.CharField(default='Popular services on JustKlick', max_length=150)),
                ('popular_services_sub', models.CharField(blank=True, max_length=255)),
                ('our_values_badge', models.CharField(default='OUR VALUES', max_length=60)),
                ('values_title', models.CharField(help_text="e.g. 'What we stand for'", max_length=200)),
                ('values_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one section should be active (published) at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are Section',
                'verbose_name_plural': 'Who We Are Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='why_choose_us/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('textarea', 'Textarea')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='dynamic.contactpage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dynamic.contactpage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dynamic.bulkpartnersection')),
            ],
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_search', to='categories.category')),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Searches',
                'ordering': ['-search_count', '-is_featured', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PromiseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Bootstrap Icon Example: bi bi-lightning-charge', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dynamic.promisesection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-check-circle', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_items', to='dynamic.whowearesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PopularService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dynamic.whowearesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(help_text='e.g. 100+, 24/7, 6+', max_length=20)),
                ('label', models.CharField(help_text='e.g. VERIFIED PARTNERS', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='dynamic.whowearesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
