# Generated by Django 6.0.6 on 2026-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whowearesection',
            name='mission_description',
            field=models.TextField(blank=True, default='mission description'),
        ),
    ]
