# Generated by Django 6.0.6 on 2026-07-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_businesslistingplanfeature'),
        ('dynamic', '0003_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBusinessSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fake', 'Fake Search')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_business_search', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Popular Business Search',
                'verbose_name_plural': 'Popular Business Searches',
                'ordering': ['-search_count', '-is_featured', 'display_order'],
            },
        ),
    ]
